In [1]:
import numpy as np

In [2]:
arr = np.arange(0,30,3) # retorna um vetor de 0 a 30 de 3 em 3

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[3] # retorna o valor do indice

9

In [6]:
arr[3:5]

array([ 9, 12])

In [7]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [8]:
arr[5:]

array([15, 18, 21, 24, 27])

In [9]:
arr[:5] + 100

array([100, 103, 106, 109, 112])

In [10]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
arr1 = np.arange(50).reshape(5,10) #criando uma matriz de 5 linhas 10 colunas 50 números sequenciais

In [15]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [16]:
arr1[:3][:] # retorna as tres primeiras linhas no primeiro colchete, e todas as colunas no seundo

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [17]:
arr1[:2, 4] # retorna os valores da coluna 4 das duas primeiras linhas

array([ 4, 14])