In [15]:
import numpy as np # importando numpy com apelido np

In [16]:
minha_lista = [1, 2, 3] # lista de 3 números

In [17]:
np.array(minha_lista) # array davariável minha_lista

array([1, 2, 3])

In [18]:
minha_matriz = [[1,2,3], [4, 5, 6], [7, 8, 9] ] #lista de listas

In [19]:
np.array(minha_matriz) # Matriz de duas dimensões da variável minha_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,10) # array de 0 a 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(0,10,2)  # array de 0 a 10 com intevalos de 2

array([0, 2, 4, 6, 8])

In [22]:
np.zeros(3) # array de 3 zeros

array([0., 0., 0.])

In [23]:
np.zeros((5,5))  # matriz de zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((3,3)) # matriz de uns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.eye(10)  # Matriz de identidade

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
np.linspace(0,10,3) # linspace mostra a range de número e determina quantos números serão mostrados no ultimo parametro

array([ 0.,  5., 10.])

In [29]:
np.linspace(0,10,5) # linspace de 5 números entre 0 e 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.random.rand(5) # mostra um array de números aleatórios 

array([0.60971423, 0.00683039, 0.9352934 , 0.28609514, 0.79165662])

In [33]:
np.random.rand(5,5,5) # Matriz de 3 dimensões gerada aleatóriamente

array([[[0.08305012, 0.34740856, 0.44664922, 0.26319555, 0.16541557],
        [0.77563981, 0.00418783, 0.90858045, 0.94272117, 0.02902001],
        [0.1377147 , 0.99456359, 0.45995853, 0.48794775, 0.50129625],
        [0.97082533, 0.39434874, 0.91622301, 0.09294274, 0.24193582],
        [0.00896361, 0.00968863, 0.67136841, 0.51107449, 0.99616489]],

       [[0.65646469, 0.38410045, 0.36800413, 0.99541289, 0.8418149 ],
        [0.66464292, 0.57989915, 0.75383526, 0.98804395, 0.41737878],
        [0.3691438 , 0.5205654 , 0.1051161 , 0.36138256, 0.0160378 ],
        [0.47259547, 0.12721142, 0.80077414, 0.42861128, 0.1644844 ],
        [0.59346743, 0.24903157, 0.42188733, 0.34316283, 0.27593331]],

       [[0.97055793, 0.18698445, 0.55623469, 0.43353356, 0.93962232],
        [0.13070438, 0.00800093, 0.64823075, 0.5239601 , 0.56543975],
        [0.86184804, 0.2315463 , 0.65079037, 0.68437811, 0.63733413],
        [0.72920751, 0.03890813, 0.72082464, 0.81547468, 0.19416731],
        [0.45262

In [34]:
np.random.randn(5) # array de números aleatórios incluindo negativos

array([ 0.16282525, -0.47325697, -0.35702371,  1.48705181, -0.57293079])

In [39]:
np.random.randint(0,100,10) # array de números inteiros aleatórios de 0 a 100 mostrando apenas 10

array([ 4, 12, 15, 27, 56, 64, 87, 17, 98, 73])

In [41]:
arr = np.random.rand(25) # vetor de tamnho 25

In [42]:
arr

array([0.11980877, 0.54531299, 0.85173184, 0.0591669 , 0.45298184,
       0.07004294, 0.67170675, 0.85859076, 0.92878548, 0.91507397,
       0.8250137 , 0.79426683, 0.22164597, 0.8371758 , 0.37692338,
       0.56717153, 0.34628415, 0.49224323, 0.52763825, 0.62704483,
       0.01947439, 0.4270683 , 0.35617968, 0.02960976, 0.62135018])

In [45]:
arr = arr.reshape(5,5) # transforma o vetor em uma matriz 5 por 5

In [46]:
arr

array([[0.11980877, 0.54531299, 0.85173184, 0.0591669 , 0.45298184],
       [0.07004294, 0.67170675, 0.85859076, 0.92878548, 0.91507397],
       [0.8250137 , 0.79426683, 0.22164597, 0.8371758 , 0.37692338],
       [0.56717153, 0.34628415, 0.49224323, 0.52763825, 0.62704483],
       [0.01947439, 0.4270683 , 0.35617968, 0.02960976, 0.62135018]])

In [47]:
arr.shape # mostra o tamanho em linhas e colunas matriz associada ao arr

(5, 5)

In [49]:
arr.max() # maior número

0.9287854823670295

In [50]:
arr.min() # menor número

0.019474393196929007

In [54]:
arr.argmax() # incide do maior número

8

In [55]:
arr.argmin() # indice do menor número

20

In [56]:
arr.mean() # média de todos os números somados

0.5016916890242653